# kvstore 配置文件

#服务端ip地址
ip = 192.168.254.100
#服务端端口
port = 2000
#服务端角色
role = master
#存储引擎
engine = array
#日志等级(DEBUG,INFO,WARN,ERROR,FATAL)
loglevel =INFO
#持久化方式(rdb,aof,none)
persistence = aof
#master_ip = 127.0.0.1
#master_port = 2000

#AOF配置
aof_fsync = always